picaMoves = ('right right right',
'right right right up',
'right right right down',
'right right right right',
'right right right right up',
'right right right right down',
'up up',
'up up right',
'up up left',
'up up right right',
'up up left left',
'up up up',
'up up up right',
'up up up left',
'up up up up',
'left left',
'left left up',
'left left left up',
'left left down down',
'up up up up up right right')

picaRoutes = (((18, 17), ),
((16, 20), (13, 9)),
((14, 23), (13, 14), (17, 6)),
((17, 15), (24, 4)),
((27, 17), ),
((29, 19), (32, 11)),
((25, 17), (33, 7), (26, 5)))